### ISSUE TITLE
Add to `$PATH`?

### ISSUE THREAD

**Issue by roke-julian-lockhart** [ivan-hc/PowerShell-appimage#1]
The AppImage has limited use if it can't be found by external software.

**Comment by ivan-hc** [comment]
Do you wish to add it in path?

### The step by step guide is this (for all apps you want to use locally without installation)
1. Create a directory in your ~/.local folder named "bin"
```
mkdir -p ~/.local/bin
```
2. Made the AppImage executable
```
chmod a+x ./*.AppImage
```
3. Place the AppImage there (maybe with a different name, maybe `pwsh` or `powershell`) 
4. Add this line to your ./.bashrc file
```
export PATH=$PATH:$(xdg-user-dir USER)/.local/bin
```
5. Launch the command from the teminal normally.

### A quick way is to use my clients, AppMan does not require root permissions
1. Install AppMan (the steps are the same above, but it is easy with this one-line command)
```
mkdir -p ~/.local/bin && echo 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' >> ~/.bashrc && wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/appman && chmod a+x ./appman && mv ./appman ~/.local/bin/appman 
```
2. Launch `appman` as a command for the first time (for example `appman -h`, the command that lists all options ), the first time AppMan will ask you where to install the apps, for example write "Applications", it will be created in your $HOME directory. You can also choose a subdirectory (for example "~/.local/my-apps") if you wont additional diretory in your main $HOME.
3. To install PowerShell use the command:
```
appman -i powershell
```
at the end of the process, you can use PowerShell from the command line using the command `powershell`. You can also launch it from your application's menu.

I have done also a video for this to help you

https://github.com/ivan-hc/PowerShell-appimage/assets/88724353/5def17cb-53b5-4a88-9b1d-6a89175abdf8


To update PowerShell to the last version from my repository, use the command
```
appman -u powershell
```
or use directly the command that updates AppMan and all the apps installed with it
```
appman -u
```

I hope you enjoy it.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/ivan-hc/PowerShell-appimage/issues/1#issuecomment-1763188933

Thanks, @ivan-hc. However, won't this not work if I use a different login shell? (`chsh -s`)? I don't always use `bash`.

**Comment by ivan-hc** [comment]
I've never done test about it, let me know if you have success.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/ivan-hc/PowerShell-appimage/issues/1#issuecomment-1763198144

It won't because most don't also use `.bashrc`. Is there a shell-independent option?

**Comment by ivan-hc** [comment]
I have no experience with chsh, is it possible to run the command `~/.local/bin/powershell` from there?

**Comment by roke-julian-lockhart** [comment]
> https://github.com/ivan-hc/PowerShell-appimage/issues/1#issuecomment-1763198593

@ivan-hc, `chsh -s` just changes the shell. However, `~/.local/bin/powershell` won't work from anywhere except `bash`, because `~` is a `bash` command. You're better off using `$HOME/.local/bin/powershell`, which should work everywhere since it's an environment variable (even in PowerShell itself, since `$Env:HOME` is abstracted to the cross-platform automatic variable `$HOME`). See https://github.com/manga-download/manga-download.github.io/pull/1#issue-1287483054:~:text=stackoverflow.com%2Fa%2F11587382%2F9731176%20provides%20specific%20explanation%20of%20why%20this%20is%20useful.%20summarily%2C%20%24home%20is%20not%20dependent%20upon%20any%20shell%20(and%20if%20invoked%20via%20powershell%2C%20is%20cross-platform)%20whereas%20~%20is%20solely%20expanded%20if%20bash%20invokes%20it

**Comment by ivan-hc** [comment]
Again, I don't know how `chsh` works. If to add something in the ~/.bashrc is not OK for that kind of shell and your issue can be solved by adding something in `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:`, you can create a symlink in `/usr/local/bin` instead
```
sudo ln -s $HOME/.local/bin/powershell /usr/local/bin/powershell
```
You can do this with "[AM](https://github.com/ivan-hc/AM-Application-Manager)", the other client, but if I remember well you are on Fedora, and if it is "immutable" you can't have the launcher in the menu (AM installs .desktop files in `/usr/share/applications`), but at least you have the program in $PATH (`/usr/local/bin`).

However I've not understand if installing my PowerShell AppImage like this solves the issue for you. All my work is focused on `bash`.

PS: remember to close this issue when it is solved.
